#ifndef VARIETAS_CODEGEN_DECOMPOSE_HPP
#define VARIETAS_CODEGEN_DECOMPOSE_HPP

#include <algorithm>
#include <cstddef>
#include <vector>

#include "varietas/codegen/factor.hpp"
#include "varietas/codegen/rational.hpp"
#include "varietas/core/ideal/buchberger.hpp"
#include "varietas/core/ideal/dimension.hpp"
#include "varietas/core/ideal/division.hpp"
#include "varietas/core/ideal/saturation.hpp"
#include "varietas/core/polynomial.hpp"

namespace varietas {

// A variety split into pieces that the algorithm finds itself.
//
// split_along separates V(I) along a hypersurface the caller names. The
// hypersurfaces worth naming are already in the ideal, as factors of its
// basis elements: if g = p_1 ... p_k lies in I, every point of V(I) lies on
// some p_i = 0, so V(I) is the union of the V(I + (p_i)). Repeating that on the
// reduced basis of each piece, until no basis element of any piece factors
// over Q, is the factorising Gröbner basis algorithm, and this is it.
//
// The pieces would repeat one another without care, since a point on both
// p_1 = 0 and p_2 = 0 lies in both. So the branch for p_i carries p_1, ...,
// p_(i-1) as polynomials that do not vanish on what it is responsible for.
// A branch in whose ideal one of those lies has nothing left to cover and is
// dropped, and a branch that no longer factors is saturated by their product
// before it is reported, which removes the parts an earlier branch has. That
// keeps the split exact: every branch is responsible for the points of its
// variety off its nonzero polynomials, the children of a split share those
// out between them, and a point of V(I) is always some branch's
// responsibility. The union of the pieces is V(I), exactly.
//
// What the pieces are not is the irreducible components of V(I), and it is
// worth being precise about the gap. A piece is a variety none of whose
// reduced basis elements factors over Q. A component can still hide inside
// it in two ways. One is a factorisation over an extension: x^2 - 2 = 0 is two
// points, but over Q the polynomial is irreducible and the piece is one. The
// other is reducibility that no single basis element shows, which takes a
// prime decomposition to find, and that is not here. What is guaranteed is
// the exact union and an ideal for each piece, from which the dimension, the
// image in the workspace and the real points are read as for any other.
//
// The decomposition is of the variety, not of the ideal. A basis element that
// is a power, or has a repeated factor, is replaced by its squarefree part,
// which describes the same points, so an order of contact the ideal recorded
// (the z^2 at the pinch of a pinched torus) is not carried into the pieces.

struct decomposition_statistics {
  std::size_t branches = 0;        // work items taken off the list
  std::size_t factorisations = 0;  // basis elements found to factor, and split along
  std::size_t empty = 0;           // branches whose ideal was the unit ideal
  std::size_t covered = 0;         // branches dropped for lying on an earlier one
  std::size_t saturations = 0;
  std::size_t redundant = 0;       // pieces dropped for lying inside another
};

template <std::size_t N, class Order>
struct variety_piece {
  // The reduced Gröbner basis under Order. No element factors over Q.
  std::vector<polynomial<rational, N, Order>> basis;
  affine_dimension<N> dimension;
};

namespace decompose_detail {

template <std::size_t N, class Order>
struct branch {
  std::vector<polynomial<rational, N, Order>> generators;
  // Polynomials that do not vanish on the part of the variety this branch
  // is responsible for.
  std::vector<polynomial<rational, N, Order>> nonzero;
  bool saturated = false;
};

// Every element of `smaller` reduces to zero modulo `basis`, so the ideal of
// `basis` contains it and the variety of `basis` lies inside its variety.
template <std::size_t N, class Order>
bool contains(const std::vector<polynomial<rational, N, Order>>& basis,
              const std::vector<polynomial<rational, N, Order>>& smaller) {
  return std::all_of(smaller.begin(), smaller.end(),
                     [&](const auto& g) { return is_member(g, basis); });
}

}  // namespace decompose_detail

// The pieces of V(I), I generated by `generators`, largest dimension first.
// An empty variety gives no pieces.
template <std::size_t N, class Order>
std::vector<variety_piece<N, Order>> decompose(
    const std::vector<polynomial<rational, N, Order>>& generators,
    decomposition_statistics* statistics = nullptr) {
  using poly = polynomial<rational, N, Order>;
  using branch = decompose_detail::branch<N, Order>;

  decomposition_statistics local;
  decomposition_statistics& counters = statistics != nullptr ? *statistics : local;

  // Polynomials already factored and found irreducible. A basis element that
  // does not factor reappears in every child of the branch it was found in.
  std::vector<poly> irreducible;
  const auto known_irreducible = [&](const poly& g) {
    return std::find(irreducible.begin(), irreducible.end(), g) != irreducible.end();
  };

  std::vector<branch> pending{branch{generators, {}, false}};
  std::vector<std::vector<poly>> found;

  while (!pending.empty()) {
    branch current = std::move(pending.back());
    pending.pop_back();
    ++counters.branches;

    const std::vector<poly> basis = groebner_basis(current.generators);
    if (is_unit_ideal(basis)) {
      ++counters.empty;
      continue;
    }
    if (std::any_of(current.nonzero.begin(), current.nonzero.end(),
                    [&](const poly& h) { return is_member(h, basis); })) {
      ++counters.covered;
      continue;
    }

    // The first element, from the smallest, that factors or is not
    // squarefree. Linear polynomials are irreducible and are not tried.
    bool split = false;
    for (auto it = basis.rbegin(); it != basis.rend() && !split; ++it) {
      const poly& g = *it;
      if (g.degree() <= 1 || known_irreducible(g)) {
        continue;
      }
      const auto factors = factor(g);
      if (factors.factors.size() == 1 && factors.factors.front().multiplicity == 1) {
        irreducible.push_back(g);
        continue;
      }
      ++counters.factorisations;
      split = true;

      // Children in the order of the factors. The i-th is responsible for
      // what lies on p_i and off p_1, ..., p_(i-1), so pushing them in reverse
      // takes the first off the list first.
      std::vector<branch> children;
      std::vector<poly> nonzero = current.nonzero;
      for (const auto& [p, multiplicity] : factors.factors) {
        (void)multiplicity;
        branch child;
        child.generators = basis;
        child.generators.push_back(p);
        child.nonzero = nonzero;
        children.push_back(std::move(child));
        nonzero.push_back(p);
      }
      for (auto child = children.rbegin(); child != children.rend(); ++child) {
        pending.push_back(std::move(*child));
      }
    }
    if (split) {
      continue;
    }

    // Nothing factors. Saturating by the nonzero polynomials removes what the
    // earlier branches already hold; the result may factor where the basis
    // did not, so it goes back on the list, once.
    if (!current.nonzero.empty() && !current.saturated) {
      ++counters.saturations;
      std::vector<poly> saturated = saturate_by_product(basis, current.nonzero);
      if (saturated != basis) {
        pending.push_back(branch{std::move(saturated), std::move(current.nonzero), true});
        continue;
      }
    }
    found.push_back(basis);
  }

  // A piece whose ideal contains another's lies inside it. Containment of
  // ideals is the test, which is sufficient for containment of varieties and
  // not necessary, so a piece inside another can survive it when only the
  // radical would show it; equal pieces keep the first.
  std::vector<bool> drop(found.size(), false);
  for (std::size_t a = 0; a < found.size(); ++a) {
    for (std::size_t b = 0; b < found.size() && !drop[a]; ++b) {
      if (a == b || drop[b]) {
        continue;
      }
      if (decompose_detail::contains(found[a], found[b]) &&
          (!decompose_detail::contains(found[b], found[a]) || b < a)) {
        drop[a] = true;
        ++counters.redundant;
      }
    }
  }

  std::vector<variety_piece<N, Order>> pieces;
  for (std::size_t a = 0; a < found.size(); ++a) {
    if (!drop[a]) {
      pieces.push_back({found[a], ideal_dimension(found[a])});
    }
  }
  std::stable_sort(pieces.begin(), pieces.end(), [](const auto& x, const auto& y) {
    return x.dimension.dimension > y.dimension.dimension;
  });
  return pieces;
}

}  // namespace varietas

#endif
