#ifndef VARIETAS_CORE_IDEAL_BUCHBERGER_HPP
#define VARIETAS_CORE_IDEAL_BUCHBERGER_HPP

#include <algorithm>
#include <cstddef>
#include <utility>
#include <vector>

#include "varietas/core/config.hpp"
#include "varietas/core/ideal/division.hpp"
#include "varietas/core/monomial.hpp"
#include "varietas/core/polynomial.hpp"

namespace varietas {

// Counters for the offline run. The number of pairs discarded by each
// criterion is the honest measure of whether an order is workable for a given
// kinematic ideal, so it is reported rather than hidden.
struct buchberger_statistics {
  std::size_t pairs_generated = 0;
  std::size_t pairs_discarded_coprime = 0;
  std::size_t pairs_discarded_chain = 0;
  std::size_t pairs_reduced = 0;
  std::size_t reductions_to_zero = 0;
};

// S-polynomial of f and g: the combination that cancels their leading terms,
//
//     S(f, g) = (L / LT(f)) f - (L / LT(g)) g,   L = lcm(LM(f), LM(g)).
template <class Coeff, std::size_t N, class Order>
polynomial<Coeff, N, Order> s_polynomial(const polynomial<Coeff, N, Order>& f,
                                         const polynomial<Coeff, N, Order>& g) {
  using poly = polynomial<Coeff, N, Order>;
  using mono = monomial<N>;
  using traits = coefficient_traits<Coeff>;

  VARIETAS_ASSERT(!f.is_zero() && !g.is_zero());

  const mono l = mono::lcm(f.leading_monomial(), g.leading_monomial());

  poly s = f.multiply_by_monomial(mono::divide(l, f.leading_monomial()),
                                  traits::inverse(f.leading_coefficient()));
  s.subtract_monomial_multiple(mono::divide(l, g.leading_monomial()),
                               traits::inverse(g.leading_coefficient()), g);
  return s;
}

namespace detail {

struct critical_pair {
  std::size_t i;
  std::size_t j;
};

}  // namespace detail

// Buchberger's algorithm with the normal selection strategy: the pending pair
// with the smallest lcm is treated first. Both of Buchberger's criteria are
// applied, so a pair is reduced only when neither of them certifies in advance
// that its S-polynomial reduces to zero. The result is a Gröbner basis of the
// ideal generated by the input, not necessarily minimal or reduced.
//
// Termination is Dickson's lemma: each new basis element strictly enlarges the
// ideal of leading terms, and an ascending chain of monomial ideals stabilises.
template <class Coeff, std::size_t N, class Order>
std::vector<polynomial<Coeff, N, Order>> buchberger(
    const std::vector<polynomial<Coeff, N, Order>>& generators,
    buchberger_statistics* statistics = nullptr) {
  using poly = polynomial<Coeff, N, Order>;
  using mono = monomial<N>;

  std::vector<poly> basis;
  basis.reserve(generators.size());
  for (const poly& f : generators) {
    if (!f.is_zero()) {
      basis.push_back(f.monic());
    }
  }

  std::vector<detail::critical_pair> pending;
  for (std::size_t i = 0; i < basis.size(); ++i) {
    for (std::size_t j = i + 1; j < basis.size(); ++j) {
      pending.push_back(detail::critical_pair{i, j});
    }
  }
  if (statistics != nullptr) {
    statistics->pairs_generated += pending.size();
  }

  const auto lcm_of = [&basis](const detail::critical_pair& p) {
    return mono::lcm(basis[p.i].leading_monomial(), basis[p.j].leading_monomial());
  };

  const auto is_pending = [&pending](std::size_t a, std::size_t b) {
    const std::size_t lo = a < b ? a : b;
    const std::size_t hi = a < b ? b : a;
    return std::any_of(pending.begin(), pending.end(), [lo, hi](const detail::critical_pair& p) {
      return p.i == lo && p.j == hi;
    });
  };

  while (!pending.empty()) {
    const auto selected = std::min_element(
        pending.begin(), pending.end(),
        [&](const detail::critical_pair& a, const detail::critical_pair& b) {
          return Order::compare(lcm_of(a), lcm_of(b)) < 0;
        });
    const detail::critical_pair pair = *selected;
    pending.erase(selected);

    const mono l = lcm_of(pair);

    // First criterion: coprime leading monomials, so lcm = product and the
    // S-polynomial reduces to zero against the two generators alone.
    if (l == basis[pair.i].leading_monomial() * basis[pair.j].leading_monomial()) {
      if (statistics != nullptr) {
        ++statistics->pairs_discarded_coprime;
      }
      continue;
    }

    // Second (chain) criterion: some third element divides the lcm and both of
    // the pairs it forms have already been treated, so this pair is redundant.
    bool chained = false;
    for (std::size_t k = 0; k < basis.size() && !chained; ++k) {
      if (k == pair.i || k == pair.j || basis[k].is_zero()) {
        continue;
      }
      chained = mono::divides(basis[k].leading_monomial(), l) && !is_pending(pair.i, k) &&
                !is_pending(pair.j, k);
    }
    if (chained) {
      if (statistics != nullptr) {
        ++statistics->pairs_discarded_chain;
      }
      continue;
    }

    const poly remainder = normal_form(s_polynomial(basis[pair.i], basis[pair.j]), basis);
    if (statistics != nullptr) {
      ++statistics->pairs_reduced;
    }

    if (remainder.is_zero()) {
      if (statistics != nullptr) {
        ++statistics->reductions_to_zero;
      }
      continue;
    }

    basis.push_back(remainder.monic());
    const std::size_t added = basis.size() - 1;
    for (std::size_t t = 0; t < added; ++t) {
      pending.push_back(detail::critical_pair{t, added});
    }
    if (statistics != nullptr) {
      statistics->pairs_generated += added;
    }
  }

  return basis;
}

// Minimalises and fully reduces a Gröbner basis in place: no leading monomial
// divides another, every element is monic, and no monomial of any element is
// divisible by the leading monomial of a different one. The reduced basis of
// an ideal is unique for a fixed order, which is what lets a generated header
// be compared against the basis it was produced from.
template <class Coeff, std::size_t N, class Order>
void reduce_groebner_basis(std::vector<polynomial<Coeff, N, Order>>& basis) {
  using poly = polynomial<Coeff, N, Order>;
  using mono = monomial<N>;

  basis.erase(std::remove_if(basis.begin(), basis.end(),
                             [](const poly& f) { return f.is_zero(); }),
              basis.end());

  // Minimalise: discard any element whose leading monomial is divisible by the
  // leading monomial of a surviving one.
  std::vector<bool> discarded(basis.size(), false);
  for (std::size_t i = 0; i < basis.size(); ++i) {
    if (discarded[i]) {
      continue;
    }
    for (std::size_t j = 0; j < basis.size(); ++j) {
      if (i == j || discarded[j]) {
        continue;
      }
      if (mono::divides(basis[j].leading_monomial(), basis[i].leading_monomial())) {
        // Equal leading monomials would discard both; keep the earlier index.
        if (basis[i].leading_monomial() != basis[j].leading_monomial() || j < i) {
          discarded[i] = true;
          break;
        }
      }
    }
  }

  std::vector<poly> minimal;
  minimal.reserve(basis.size());
  for (std::size_t i = 0; i < basis.size(); ++i) {
    if (!discarded[i]) {
      minimal.push_back(basis[i].monic());
    }
  }

  // Reduce each element against the others; leading monomials are unaffected,
  // so the reduction may be performed sequentially in place.
  for (std::size_t i = 0; i < minimal.size(); ++i) {
    minimal[i] = normal_form_excluding(minimal[i], minimal, i).monic();
  }

  std::sort(minimal.begin(), minimal.end(), [](const poly& a, const poly& b) {
    return Order::compare(a.leading_monomial(), b.leading_monomial()) > 0;
  });

  basis = std::move(minimal);
}

// The reduced Gröbner basis of the ideal generated by the input. A basis equal
// to {1} certifies that the ideal is the whole ring, that is, that the system
// has no solution over the algebraic closure (weak Nullstellensatz).
template <class Coeff, std::size_t N, class Order>
std::vector<polynomial<Coeff, N, Order>> groebner_basis(
    const std::vector<polynomial<Coeff, N, Order>>& generators,
    buchberger_statistics* statistics = nullptr) {
  std::vector<polynomial<Coeff, N, Order>> basis = buchberger(generators, statistics);
  reduce_groebner_basis(basis);
  return basis;
}

// Ideal membership. Sound only when basis is a Gröbner basis of the ideal.
template <class Coeff, std::size_t N, class Order>
bool is_member(const polynomial<Coeff, N, Order>& f,
               const std::vector<polynomial<Coeff, N, Order>>& basis) {
  return normal_form(f, basis).is_zero();
}

// True when the basis generates the unit ideal, that is, when the variety is
// empty over the algebraic closure.
template <class Coeff, std::size_t N, class Order>
bool is_unit_ideal(const std::vector<polynomial<Coeff, N, Order>>& basis) {
  for (const polynomial<Coeff, N, Order>& f : basis) {
    if (!f.is_zero() && f.leading_monomial().is_one()) {
      return true;
    }
  }
  return false;
}

}  // namespace varietas

#endif
