#ifndef VARIETAS_CORE_IDEAL_DIMENSION_HPP
#define VARIETAS_CORE_IDEAL_DIMENSION_HPP

#include <array>
#include <cstddef>
#include <vector>

#include "varietas/core/config.hpp"
#include "varietas/core/monomial.hpp"
#include "varietas/core/polynomial.hpp"

namespace varietas {

// The dimension of V(I), read off the leading terms.
//
// Until now the library asked one question of a variety's size, whether it is
// finite, because that is the question inverse kinematics asks, and the
// finiteness criterion answers it from the leading monomials alone. The
// singular locus asks the general one. A singular set is almost never finite:
// for a planar arm it is a circle's worth of configurations, for a spatial arm
// a surface, and reporting "not zero dimensional" of both says nothing about
// either.
//
// The general statement is that dim V(I) = dim V(LT(I)), and that for a
// monomial ideal the dimension is combinatorial: it is the largest number of
// variables that the ideal does not constrain at all. Precisely, a subset S of
// the variables is *independent* modulo I when LT(I) ∩ k[S] = (0), and
//
//     dim V(I) = max { |S| : S independent }.
//
// (Cox, Little and O'Shea, Chapter 9, §1.) The intersection LT(I) ∩ k[S] is
// generated by those generators of LT(I) that involve no variable outside S, so
// independence is decided by inspecting supports: S is independent exactly when
// no leading monomial of the basis is supported inside S. Nothing is computed
// beyond the Gröbner basis that was needed anyway, and the answer does not
// depend on the monomial order, though the basis certainly does.
//
// The empty variety falls out of the same statement rather than needing a case.
// If I is the unit ideal then 1 is a leading monomial, its support is empty and
// therefore contained in every S, so no subset is independent, not even the
// empty one, and the maximum is over an empty set. That is reported as
// is_empty rather than as a dimension of zero, which is what a point would be.

template <std::size_t N>
struct affine_dimension {
  // The variety has no points over the algebraic closure, so it has no
  // dimension. Reported separately because -1 as a size is a lie waiting to be
  // told, and because empty and zero dimensional are the two answers a caller
  // most needs to keep apart.
  bool is_empty = false;

  // dim V(I) over the algebraic closure of the coefficient field.
  std::size_t dimension = 0;

  // A set of variables of that size which the ideal leaves unconstrained. Its
  // complement is a set of coordinates on which V(I) is finite over the rest,
  // so it names *which* freedom the variety has and not only how much: for a
  // singular locus, which joints are still free to move along it.
  std::array<bool, N> independent{};

  bool is_zero_dimensional() const noexcept { return !is_empty && dimension == 0; }
};

// Dimension from a Gröbner basis. Any Gröbner basis will do, reduced or not,
// since only the leading monomials are consulted and they generate LT(I)
// either way.
//
// The search is over all 2^N subsets. N is the number of ring variables, which
// for the constructions here is two per joint plus the pose coordinates, so the
// exhaustive search is a few thousand support tests and is not worth replacing
// with the usual branch and bound until it is.
template <class Coeff, std::size_t N, class Order>
affine_dimension<N> ideal_dimension(const std::vector<polynomial<Coeff, N, Order>>& basis) {
  static_assert(N < 32, "exhaustive independent-set search is exponential in the variables");

  // Supports of the leading monomials, as bit masks.
  std::vector<unsigned long> supports;
  supports.reserve(basis.size());
  for (const auto& g : basis) {
    if (g.is_zero()) {
      continue;
    }
    const monomial<N>& lm = g.leading_monomial();
    unsigned long support = 0;
    for (std::size_t i = 0; i < N; ++i) {
      if (lm[i] != 0) {
        support |= 1ul << i;
      }
    }
    supports.push_back(support);
  }

  affine_dimension<N> result;
  result.is_empty = true;

  const unsigned long subsets = 1ul << N;
  for (unsigned long s = 0; s < subsets; ++s) {
    bool independent = true;
    for (const unsigned long support : supports) {
      // A leading monomial supported inside S is a nonzero element of
      // LT(I) ∩ k[S], and S is then dependent. The unit ideal's leading
      // monomial has empty support and fails this for every S, including the
      // empty one.
      if ((support & ~s) == 0) {
        independent = false;
        break;
      }
    }
    if (!independent) {
      continue;
    }

    std::size_t size = 0;
    for (std::size_t i = 0; i < N; ++i) {
      size += (s >> i) & 1ul;
    }
    if (result.is_empty || size > result.dimension) {
      result.is_empty = false;
      result.dimension = size;
      for (std::size_t i = 0; i < N; ++i) {
        result.independent[i] = ((s >> i) & 1ul) != 0;
      }
    }
  }

  return result;
}

}  // namespace varietas

#endif
