// The decoupled solver, put back together and run against the arm it came from.
//
// The generated header below solves only the reduced problem: shoulder and
// elbow against a radius and a height. The base angle is recovered here, by an
// arctangent, and the two halves are combined into a solver for the whole arm.
// That combination is deliberately written out by hand rather than generated,
// because this is the first thing that has to be shown to work before it is
// worth emitting.
//
// The check is the only one that matters for an inverse kinematics solver:
// drive the joints to a returned configuration and the tool has to be where it
// was asked to go. Forward kinematics here is the numerical map in
// varietas_kinematics — trigonometry on doubles, no ideal, no matrix.

#include <array>
#include <cmath>
#include <cstddef>
#include <vector>

#include <gtest/gtest.h>

#include "varietas/kinematics/evaluate.hpp"
#include "varietas/kinematics/rationalize.hpp"

#include "arms.hpp"
#include "anthropomorphic_reduced.hpp"  // generated by generate_spatial_3r

namespace {

using reduced = varietas_generated::anthropomorphic_reduced;

varietas::chain<double> numeric_arm() {
  return varietas::chain_cast<double>(varietas_test::anthropomorphic_three_link());
}

std::array<double, 3> tool_position(const std::array<double, 3>& q) {
  const std::vector<double> angles{q[0], q[1], q[2]};
  const auto frame = varietas::forward_kinematics(numeric_arm(), angles);
  return {frame.translation()[0], frame.translation()[1], frame.translation()[2]};
}

// The base joint turns about z, so it sweeps x into y and leaves z alone. The
// reduced problem is posed at a radius measured in the plane and the height
// straight off the target.
//
// Each solution of the reduced problem gives a configuration of the whole arm
// twice: once with the plane turned to face the target, and once turned half
// a turn further, with the radius then measured backwards. Both are genuine —
// they are the "forward" and "reversed" postures of the arm.
std::vector<std::array<double, 3>> solve_whole_arm(double x, double y, double z) {
  std::vector<std::array<double, 3>> configurations;

  const double radius = std::hypot(x, y);
  const double heading = std::atan2(y, x);

  const double families[2][2] = {{radius, heading}, {-radius, heading + M_PI}};
  for (const auto& family : families) {
    const double pose[2] = {family[0], z};
    std::array<double, 4> out{};
    reduced::status state{};
    const int count = reduced::solve(pose, out.data(), 2, &state);
    if (count < 0) {
      continue;  // this pose is off the chart the reduced basis describes
    }
    for (int k = 0; k < count; ++k) {
      configurations.push_back({family[1],
                                varietas::angle_from_variable(out[k * 2 + 0]),
                                varietas::angle_from_variable(out[k * 2 + 1])});
    }
  }
  return configurations;
}

// --- the reduced header describes the reduced problem ----------------------

TEST(GeneratedDecoupled, ShapeSurvivedTheRoundTrip) {
  EXPECT_EQ(reduced::num_unknowns, 2u);
  EXPECT_EQ(reduced::num_parameters, 2u);
  EXPECT_EQ(reduced::dimension, 2u);
  EXPECT_STREQ(reduced::order_name, "grevlex");
}

// --- and the two halves together solve the arm -----------------------------

TEST(GeneratedDecoupled, EveryConfigurationReachesTheRequestedPoint) {
  // A point comfortably inside the reachable shell and off every axis.
  const double x = 1.1, y = 0.5, z = 0.4;

  const auto configurations = solve_whole_arm(x, y, z);
  ASSERT_FALSE(configurations.empty()) << "no configuration returned";

  for (const auto& q : configurations) {
    const auto reached = tool_position(q);
    EXPECT_NEAR(reached[0], x, 1e-8);
    EXPECT_NEAR(reached[1], y, 1e-8);
    EXPECT_NEAR(reached[2], z, 1e-8);
  }
}

TEST(GeneratedDecoupled, TheArmHasFourPosturesAtAGeneralPoint) {
  // Elbow up and elbow down, each facing forwards and reversed. This is the
  // count the decoupled solve reports as `branches`, and the same count that
  // solving the whole system over Q at a fixed pose gives.
  const auto configurations = solve_whole_arm(1.1, 0.5, 0.4);
  EXPECT_EQ(configurations.size(), 4u);

  // All four are genuinely different postures, not one repeated.
  for (std::size_t i = 0; i < configurations.size(); ++i) {
    for (std::size_t j = i + 1; j < configurations.size(); ++j) {
      double separation = 0.0;
      for (std::size_t k = 0; k < 3; ++k) {
        separation += std::abs(configurations[i][k] - configurations[j][k]);
      }
      EXPECT_GT(separation, 1e-6) << "configurations " << i << " and " << j << " coincide";
    }
  }
}

TEST(GeneratedDecoupled, AgreesWithTheForwardMapAcrossTheWorkspace) {
  // A sweep in three dimensions. One point is a weak test of a basis that
  // claims to hold at every radius and height.
  int points_checked = 0;
  for (int i = -4; i <= 4; ++i) {
    for (int j = -4; j <= 4; ++j) {
      for (int k = -4; k <= 4; ++k) {
        const double x = 0.35 * i, y = 0.35 * j, z = 0.35 * k;
        const double radius = std::hypot(x, y);
        const double reach = std::hypot(radius, z);
        if (reach < 0.3 || reach > 1.85 || radius < 0.2) {
          continue;  // off the boundary spheres, and away from the axis itself
        }

        const auto configurations = solve_whole_arm(x, y, z);
        if (configurations.empty()) {
          continue;  // the guard refused this pose; that is its business
        }
        ++points_checked;

        for (const auto& q : configurations) {
          const auto reached = tool_position(q);
          EXPECT_NEAR(reached[0], x, 1e-7) << "at (" << x << ", " << y << ", " << z << ")";
          EXPECT_NEAR(reached[1], y, 1e-7) << "at (" << x << ", " << y << ", " << z << ")";
          EXPECT_NEAR(reached[2], z, 1e-7) << "at (" << x << ", " << y << ", " << z << ")";
        }
      }
    }
  }
  EXPECT_GT(points_checked, 100) << "the sweep should not have been nearly empty";
}

TEST(GeneratedDecoupled, PointsBeyondReachHaveNoConfiguration) {
  // The arm's links are of unit length, so nothing further than two units out
  // is reachable and the reduced solutions are complex there.
  const auto configurations = solve_whole_arm(3.0, 0.0, 0.0);
  EXPECT_TRUE(configurations.empty());
}

}  // namespace
